# Generated by Django 5.0.1 on 2024-01-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_prompt', models.TextField()),
            ],
        ),
    ]
