# Generated by Django 5.0.1 on 2024-01-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_homescreen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeScreen',
        ),
    ]
